server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/stockbet}
    username: ${DB_USER:stockbet}
    password: ${DB_PASS:stockbet}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false
  flyway:
    enabled: true

jwt:
  secret: ${JWT_SECRET:change-me-super-secret}
  ttlSeconds: 86400
